### PR TITLE
Email Handler

### PR DESCRIPTION
**Pull request by baldeosinghm**
# Email Handler

This pull request adds the email handler module to the plugin in the directory `src/email`.  While not connected to the database it is capable of sending emails to any email.  This does not solve the email functionality issue, but it a in progress fix.

## Type of Change

Please describe the pull request as one of the following: 

- [ ] Bug fix
- [ ] Breaking change
- [x] New feature
- [ ] Documentation update
- [ ] Testing: Test cases were made in `test_arguments.py`

## Tags

@moorej2  - Created the email module.

### CODE REVIEW

**Review by moorej2 — APPROVED** [review]

**Review by bristola — CHANGES_REQUESTED** [review]
Small change. Have the email receiver variable that the function uses to send an email to be a parameter to the function rather than a variable in the config file. This way it would be easier to automatically send emails through the web server to any student we want.

**Comment by lussierc** [comment]
@bristola, I agree. I think that this would make it easier for our purposes. It would be a quick fix.

Other than that I think it looks good.

**Comment by lussierc** [comment]
> Small change. Have the email receiver variable that the function uses to send an email to be a parameter to the function rather than a variable in the config file. This way it would be easier to automatically send emails through the web server to any student we want.

@bristola, I updated the function to take in the email receivers as a parameter. I did, however, leave the email sender information (email & password) in the config file.

**Review by lussierc — COMMENTED** [review]
Overall, the code looks good.

I have tested the function multiple times with two of my emails and it has functioned as intended, with no issue.

**Review by lussierc — APPROVED** [review]

**Pull request merged**
